version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile

  catalogdb:
   image: mongo
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Basket.API/Dockerfile
  
  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  basketdb:
   image: redis:alpine

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering.Api/Ordering.API/Dockerfile

  account.api:
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Services/Account.Api/Dockerfile

  ocelotgateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: Services/OcelotGateway/Dockerfile

  existence.grpc:
    image: ${DOCKER_REGISTRY-}existencegrpc
    build:
      context: .
      dockerfile: Services/Existence.Grpc/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine

volumes:
  mongo_data:




